lisa._assets.kmodules.lisa: follow latest upstream
ARM-software/lisa pull request #2161
Opened 2024-01-02 14:05 UTC by honxia02

Upstream has completely removed struct util_est. Now util_est is just an unsigned int field.

2024-01-02 14:42 UTC, douglas-raillard-arm commented
I see that this change also renames event fields. Do we really want to do that ? If so this needs to come with the the fixes everywhere it's required in LISA, and ensure it goes through an analysis method that will deal with backward compat of event format.

2024-01-02 14:53 UTC, douglas-raillard-arm requested changes

2024-01-02 14:53 UTC, douglas-raillard-arm commented on lisa/_assets/kmodules/lisa/ftrace_events.h
> +		__entry->util_est	= avg->util_est;
This won't fly on less recent kernel, this needs to be done based on the type

2024-01-02 14:58 UTC, douglas-raillard-arm commented
The commit message will need to be updated to add the FIX tag (see history).

2024-01-24 13:06 UTC, honxia02 commented
Closed, because so far the conclusion is that the behavior of the trace event has changed and it's not a good idea to modify the old ones. Instead we should treat this as a new signal.

2024-01-24 13:06 UTC, closed without merging